site_name: 周易 64 卦
site_description: 周易-易经 64 卦详解
dev_addr: "127.0.0.1:8080"
# repo_url: https://github.com/sunls2/zhouyi/
# repo_name: sunls2/zhouyi

nav:
  - 首页: /zhouyi/other
  - AI 占卜: https://starloom.ai
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - minify:
      minify_html: true
extra:
  generator: false
  footer_content: © 2025 NXG Company. All rights reserved.
extra_css:
  - assets/css/ui.css
  - https://gw.alipayobjects.com/os/k/font/lxgwwenkaiscreenr.css
theme:
  name: material
  custom_dir: custom_theme/
  language: zh
  favicon: assets/images/favicon.ico
  icon:
    logo: material/yin-yang
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
